# Generated by Django 3.0.3 on 2020-04-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('material', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('img_url', models.CharField(max_length=30)),
            ],
        ),
    ]
